### ISSUE TITLE
Always load google web fonts?

### ISSUE THREAD

**Issue by waynehoover** [ajkochanowicz/kickstart#175]
Hello,

I would like to use kickstart, but I don't necessarily want to use the google web fonts that are always being pulled: https://github.com/ajkochanowicz/kickstart/blob/master/lib-core/sass/themes/default/theme.sass#L25

Is there a way to disable this with some sort of option compile time? This web call actually slows down my website, and the option to change it would be nice.

**Comment by ajkochanowicz** [comment]
Good point. There should be a way to use this without pulling from GWF. I'm not near my computer at the moment, but let me see what I can do about that this afternoon.

—

**Comment by ajkochanowicz** [comment]
It looks like putting an import directive inside and if statement is a contentious issue in the sass community, and it may result in bugs. 


https://github.com/sass/sass/issues/451




However, I do think the feature you describe should exist. What would you think if I just created a second version of the default theme that didn't have Google web fonts?




You can also follow the documentation on creating your own theme. Which is actually easier than you think. I've made some videos on the documentation page to help. 




http://getkickstart.com/docs/3.x/creating-extensions/


—

**Comment by ajkochanowicz** [comment]
Also, if you don't plan on making a lot of extensions for kickstart, you can just skip to the theme section on that page.


http://getkickstart.com/docs/3.x/creating-extensions/#themes


—

**Comment by ajkochanowicz** [comment]
@waynehoover Here's an alternative you can use: http://kickstart.everything.io/extensions/11

I'll keep you posted if I can find a better solution.

**Comment by waynehoover** [comment]
@ajkochanowicz thanks! Much appreciated. I think just making my own theme is probably the best way to do it. Keep up the good work here. I'm fine to just go ahead and close this issue.

**Comment by ajkochanowicz** [comment]
Glad that could work for you!
