### ISSUE TITLE
Undefined heading mixins in Rails

### ISSUE THREAD

**Issue by anthonylebrun** [ajkochanowicz/kickstart#177]
First off, really great framework. I really appreciate the thought you've put into it and it all just makes a lot of sense to me. One little oopsie I've come into:

I installed and set up the gem as prescribed [here](http://getkickstart.com/docs/3.x/#rails) and mixins seem to work generally with the exception of the decoupled heading mixins.

    h1
      @include md-heading()

(I'm using the Sass syntax)

At which point I would get a `ActionView::Template::Error (Undefined mixin 'md-heading'.)`

**Comment by ajkochanowicz** [comment]
I think you want `heading_md`

**Comment by anthonylebrun** [comment]
Oh awesome! I guess the docs are just a bit behind:

http://getkickstart.com/docs/3.x/ui/typography/

If those are hosted on a public repo I'd be happy to create a pull request for you.

**Comment by ajkochanowicz** [comment]
Oh shoot! I didn't notice this. I'll fix this now...

**Comment by ajkochanowicz** [comment]
Okay, should be fixed now.

**Comment by anthonylebrun** [comment]
I noticed! Although I think you meant heading_md() rather than heading-md()?

I prefer the heading-md naming convention though, it's more consistent with your other mixins.

**Comment by ajkochanowicz** [comment]
They should both work, actually. It's a Sass thing.
